### ISSUE TITLE
Define use cases and useful commands

### ISSUE THREAD

**Issue by Sebobo** [Sebobo/Shel.Neos.CommandBar#10]
# Use cases and ideas

- Edit / Preview
  - [x] Quickly switch preview modes to view a page in different states (suggested by @jonnitto)
    - [x] Allow moving / dragging the command bar to not cover the content   
  - [x] Open preview for current document  (suggested by @PRGfx)
    
- Editing    
  - [ ] Quickly open create node dialog while working on a content node to continue with the next part of content
    - [x] Open create dialog command
    - [ ] Open command bar while inline editing and having create node as "recommended" command (relates to #8)
  - [x] Reload guest frame (via hotkey inclusion)

- Navigation
  - [x] Quickly navigate to another document (see #3) 
  - [x] Quickly navigate to a module and sites
    - [x] Also allow to navigate between and back from a module (needs separate plugin with reduced command set)
  - [x] Integrate Neos docs  (see #26)
  - [x] Integrate Neos package search (see #27)

- Extensibility  
  - [x] Plugin system for 3rd party commands (see #12)
    - [x] Start with Neos.Terminal as first command source (see #12)

- Languages   
  - [ ] Quickly switch language / dimension (see #1)  

- Workspaces
  - [x] Publish / Discard changes (see #6)
  - [x] Switch to another workspace (see #6) (suggested by @PRGfx)
  - [ ] Switch to workspace review (see #6)

**Comment by Sebobo** [comment]
Hi @PRGfx, thx for the ideas. Some notes:

* "Reload guest frame" is already available with the `Reload ContentCanvas` as I load all hotkeys as commands (and filter a lot out which don't work).
If it doesn't seem to be a big benefit to load the hotkeys as commands, we could of course choose the useful ones and implement the in the plugin itself as command to improve UX. `ContentCanvas` is probably not a useful term for most users.

* "Reload node-trees", why would this be helpful? Shouldn't it be rare for the tree to get out-of-sync, or is the use case rather that more people work in parallel and one wants to see the newly added or removed elements by the other?

**Comment by PRGfx** [comment]
Oh I didn't notice the hotkey actions are already available, cool.
Some naming could probably improved, yes (for example "Live" for the preview mode isn't really descriptive imo, but thats off topic).

As for the node-trees: true, I mostly used this after migrations etc when I don't want to reload the whole backend ^^ But good point with updating changes from editors.
It was more a thought about how most actions should probably also be available to fuzzy search and the ones without context (i.e. not depending on the selected node etc) are probably lower hanging fruits, but in fact the usefulness is probably limited – as long as the overall tabbability of the backend is a bit difficult, I feel like I would still need to click buttons a lot anyways.
